"""“automated”

Revision ID: b95401cdf055
Revises: 
Create Date: 2018-04-01 22:11:15.242461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b95401cdf055'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('role_type', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('value'),
    sa.UniqueConstraint('label'),
    sa.UniqueConstraint('role_type')
    )
    op.create_index(op.f('ix_role_value'), 'role', ['value'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('twitter', sa.String(length=64), nullable=True),
    sa.Column('resigned', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_index(op.f('ix_user_resigned'), 'user', ['resigned'], unique=False)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=True)
    op.create_table('promise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=128), nullable=True),
    sa.Column('actionable', sa.Boolean(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promise_actionable'), 'promise', ['actionable'], unique=False)
    op.create_table('update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=128), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('general', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update')
    op.drop_index(op.f('ix_promise_actionable'), table_name='promise')
    op.drop_table('promise')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_resigned'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_value'), table_name='role')
    op.drop_table('role')
    # ### end Alembic commands ###
