"""Added more fields for user

Revision ID: bb5b73a4486e
Revises: 6ed54c9f6773
Create Date: 2018-03-30 16:06:19.246339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb5b73a4486e'
down_revision = '6ed54c9f6773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_type', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role_type')
    # ### end Alembic commands ###
