"""Added last seen for user model

Revision ID: c297f3fd2f4b
Revises: 75e2f8b8f1ee
Create Date: 2018-03-31 18:51:41.478564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c297f3fd2f4b'
down_revision = '75e2f8b8f1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
